//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SupermarketChainMySQL.Data.Contracts;

namespace SupermarketChainMySQL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SupermarketChainEntitiesMySQL : DbContext, ISupermarketMySQLEntities
    {
        public SupermarketChainEntitiesMySQL()
            : base("name=SupermarketChainEntitiesMySQL")
        {
        }
    
        public IDbSet<Product> Products { get; set; }
        public IDbSet<Vendor> Vendors { get; set; }

        public new IDbSet<T> Set<T>() where T : class
        {
            return base.Set<T>();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    }
}
