//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketChainOracle.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupermarketOracleEntities : DbContext
    {
        public SupermarketOracleEntities()
            : base("name=SupermarketOracleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MEASURE> MEASURES { get; set; }
        public DbSet<PRODUCT> PRODUCTS { get; set; }
        public DbSet<VENDOR> VENDORS { get; set; }
    }
}
